model:
  name: 'ieee'
  pretrained: True
  load_weights: r"E:\reidCode\AAAI 2022-master\log\others\RGBNT201-seed1\multiModal_resnet50_RGBNT_concat_Sgate_sgd_margin3_cudnn\model\model.pth.tar-30"

data:
  type: 'image'
  sources: ['RGBNT201']
  targets: ['RGBNT201']
  height: 256
  width: 128
  combineall: False
  workers: 0
  transforms: ['random_flip']
  save_dir: 'log\tsne'

loss:
  name: 'margin'
  softmax:
    label_smooth: True
  ieee_margin: 1
  weight_m: 1.0
  weight_x: 1.0

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4

train:
  optim: 'sgd'
  lr: 0.001
  max_epoch: 60
  batch_size: 8
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'multi_step'
  stepsize: [15, 40]
  print_freq: 90

test:
  batch_size: 50
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: True
  eval_freq: 5
  visrank: True
  ranks: [1, 5, 10]
  rerank: False
