model:
  name: 'hamnet'
  pretrained: True

data:
  type: 'image'
  sources: ['market_to_RGBNT201']
  targets: ['market_to_RGBNT201']
  height: 256
  width: 128
  combineall: False
  workers: 0
  transforms: ['random_flip']
  save_dir: 'log\Market\hamnet'

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  weight_t: 1.0
  weight_x: 1.0


sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4



train:
  optim: 'sgd'
  lr: 0.001
  max_epoch: 120
  batch_size: 32
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'multi_step'
  stepsize: [10]
  print_freq: 100

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 8
  ranks: [1, 5, 10]
  rerank: False

