model:
  name: 'resnet50_fc512'
  pretrained: True

data:
  type: 'image'
  sources: ['RGBNT201']
  targets: ['RGBNT201']
  height: 256
  width: 128
  combineall: False
  workers: 0
  transforms: ['random_flip']
  save_dir: 'log\SOTA\RGBNT_resnet50_fc512'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True
  ieee_margin: 3
  weight_m: 1.0
  weight_x: 1.0

sampler:
  train_sampler: 'RandomIdentitySampler'
  num_instances: 4

train:
  optim: 'sgd'
  lr: 0.001
  max_epoch: 80
  batch_size: 8
  fixbase_epoch: 0
  open_layers: ['classifier']
  lr_scheduler: 'multi_step'
  stepsize: [20, 40]
  print_freq: 90

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  ranks: [1, 5, 10]
  rerank: False

